name: mist
channels:
  - PyTorch
  - conda-forge
  - defaults
dependencies:
  - numpy=1.21.2
  - pip=21.2.4
  - python=3.8.12
  - pytorch=1.10.2
  - pip:
      - mlflow==1.16.0
      - torchmetrics==0.3.1
      - transformers==4.5.0
